FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache tini

COPY package*.json ./
RUN npm install

COPY nodemon.json ./
COPY tsconfig.json ./
COPY src ./src

EXPOSE 3001

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["npm", "run", "dev"]
