on: 
  push:
    paths:
      - 'Spajzka.WEB/**'
    branches:
      - master
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Spajzka.WEB
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run cibuild

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: vazacdaniel.com
          local-dir: Spajzka.WEB/build/
          server-dir: sub/spajzka.vazacdaniel.com/
          username: github@vazacdaniel.com
          password: ${{ secrets.FTP_GITHUB_PASS }}
