import express, { Request, Response, NextFunction } from "express";
import mongoose from "mongoose";
import cors from "cors";
import helmet from "helmet";
import swaggerUi from "swagger-ui-express";
import config from "./config/config";

// Express setup
const app = express();
app.use(express.json());
app.use(cors());
app.use(helmet());

// Connect to MongoDB
mongoose
  .connect(config.mongoUri)
  .then(() => console.log("MongoDB connected"))
  .catch((err) => console.error("MongoDB connection error:", err));

// Since you don't have tsoa set up yet, create a placeholder for RegisterRoutes
// Later, this will be auto-generated by tsoa
function RegisterRoutes(app: express.Express) {
  // This will be replaced by the generated routes
  app.get('/api/v1/health', (_req, res) => {
    res.json({ status: 'ok' });
  });
}

// Register routes
RegisterRoutes(app);

// Swagger documentation - fix the import issue with proper error handling
let swaggerDocument;
try {
  swaggerDocument = require("../public/swagger.json");
} catch (error) {
  console.warn("Warning: Swagger document not found. API docs won't be available.");
}

swaggerUi.setup(swaggerDocument)

app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));

// Error handling middleware
app.use((err: any, _req: Request, res: Response, _next: NextFunction) => {
  console.error(err.stack);
  res.status(err.status || 500).json({
    message: err.message,
    errors: err.errors,
  });
});

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
