swagger: "2.0"
info:
  title: Spajzka API
  description: Spajzka API documentation
  version: 0.1.0
definitions: {}
paths:
  /item:
    get:
      summary: Get item
      description: Get item
      tags:
        - item
      responses:
        "200":
          description: Default Response
          schema:
            type: object
            properties:
              item:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  price:
                    type: number
                  quantity:
                    type: number
                  description:
                    type: string
                required:
                  - id
                  - name
                  - price
                  - quantity
                  - description
                additionalProperties: false
host: 127.0.0.1:3010
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  apiKey:
    type: apiKey
    name: apiKey
    in: header
