on:
  push:
    paths:
      - "apps/api/**"
    branches:
      - master
name: 🚀 Deploy api on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: "Install dependencies"
        run: |
          npm install

      - name: 🔨 Build Project
        run: |
          cd ./apps/api
          CI=false npm run build

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "MONGO_CONNECTION_STRING"
          replace: "${{ secrets.MONGO_CONNECTION_STRING }}"
          include: "apps/api/.env.production"

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: vazacdaniel.com
          local-dir: apps/api/
          server-dir: sub/api.spajzka.vazacdaniel.com/
          username: github@vazacdaniel.com
          password: ${{ secrets.FTP_GITHUB_PASS }}
          exclude: |
            **/node_modules/**
            .env.development