on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run cibuild

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: vazacdaniel.com
          local-dir: build/
          server-dir: sub/spajzka.vazacdaniel.com/
          username: github@vazacdaniel.com
          password: ${{ secrets.FTP_GITHUB_PASS }}